package com.turkcell.cdrgenerator1.generator;

import com.turkcell.cdrgenerator1.model.AsnField;
import com.turkcell.cdrgenerator1.model.BerTagClass;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

class CdrRecordBuilderTest {

    // buildRecordFromFields does not touch the registry, so the parser
    // dependency can stay null for these unit tests.
    private final CdrRecordBuilder builder = new CdrRecordBuilder(null, new FieldValueGenerator());

    private AsnField leaf(String name, String type) {
        return AsnField.builder().fieldName(name).fieldType(type)
                .tagNumber(1).tagClass(BerTagClass.CONTEXT).build();
    }

    @Test
    void userValuesOverrideGeneratedOnes() {
        Map<String, Object> record = builder.buildRecordFromFields(
                List.of(leaf("msisdn", "IA5String")),
                Map.of("msisdn", "905321234567"));
        assertEquals("\"905321234567\"", record.get("msisdn"));
    }

    @Test
    void missingUserValuesAreAutoGenerated() {
        Map<String, Object> record = builder.buildRecordFromFields(
                List.of(leaf("msisdn", "IA5String")), Map.of());
        String value = (String) record.get("msisdn");
        assertTrue(value.startsWith("\"") && value.endsWith("\""));
        assertTrue(value.length() > 2);
    }

    @Test
    void integerLeavesAreWrappedAsDecimalLiterals() {
        Map<String, Object> record = builder.buildRecordFromFields(
                List.of(leaf("duration", "INTEGER")), Map.of("duration", "42"));
        assertEquals("'42'D", record.get("duration"));
    }

    @Test
    void booleanLeavesStayQuotedForTypeAwareEncoding() {
        Map<String, Object> record = builder.buildRecordFromFields(
                List.of(leaf("flag", "BOOLEAN")), Map.of("flag", "1"));
        assertEquals("\"1\"", record.get("flag"));
    }

    @Test
    void nestedFieldsBuildNestedMaps() {
        AsnField parent = AsnField.builder()
                .fieldName("addr").fieldType("Address")
                .tagNumber(0).tagClass(BerTagClass.CONTEXT)
                .children(List.of(leaf("ton", "INTEGER"), leaf("msisdn", "IA5String")))
                .build();

        Map<String, Object> record = builder.buildRecordFromFields(
                List.of(parent), Map.of("ton", "3"));

        Map<?, ?> addr = assertInstanceOf(Map.class, record.get("addr"));
        assertEquals("'3'D", addr.get("ton"));
        assertTrue(addr.containsKey("msisdn"));
    }

    @Test
    void repeatedFieldsBuildBetweenOneAndTwoElements() {
        AsnField repeated = AsnField.builder()
                .fieldName("items").fieldType("Inner").repeated(true)
                .tagNumber(6).tagClass(BerTagClass.CONTEXT)
                .children(List.of(leaf("a", "INTEGER")))
                .build();

        for (int i = 0; i < 20; i++) {
            Map<String, Object> record = builder.buildRecordFromFields(List.of(repeated), Map.of());
            List<?> items = assertInstanceOf(List.class, record.get("items"));
            assertTrue(items.size() >= 1 && items.size() <= 2,
                    "repeat count must stay within [1,2], was " + items.size());
        }
    }

    @Test
    void repeatedPrimitiveLeafBuildsValueList() {
        AsnField repeatedLeaf = AsnField.builder()
                .fieldName("attrs").fieldType("IA5String").repeated(true)
                .tagNumber(5).tagClass(BerTagClass.CONTEXT).build();

        Map<String, Object> record = builder.buildRecordFromFields(List.of(repeatedLeaf), Map.of());
        List<?> values = assertInstanceOf(List.class, record.get("attrs"));
        assertTrue(values.size() >= 1 && values.size() <= 2);
        for (Object value : values) {
            String text = assertInstanceOf(String.class, value);
            assertTrue(text.startsWith("\"") && text.endsWith("\""));
        }
    }

    @Test
    void userValueOnRepeatedLeafBecomesSingleElementList() {
        AsnField repeatedLeaf = AsnField.builder()
                .fieldName("attrs").fieldType("IA5String").repeated(true)
                .tagNumber(5).tagClass(BerTagClass.CONTEXT).build();

        Map<String, Object> record = builder.buildRecordFromFields(
                List.of(repeatedLeaf), Map.of("attrs", "HELLO"));
        assertEquals(List.of("\"HELLO\""), record.get("attrs"));
    }

    @Test
    void fieldOrderIsPreserved() {
        Map<String, Object> record = builder.buildRecordFromFields(
                List.of(leaf("first", "INTEGER"), leaf("second", "IA5String"), leaf("third", "INTEGER")),
                Map.of());
        assertEquals(List.of("first", "second", "third"), List.copyOf(record.keySet()));
    }
}
