
server.port=8080
server.servlet.context-path=/cdr-generator


spring.application.name=cdr-generator1
app.cdr.data-structure-path=datastructure.json


app.cdr.default-record-count=1
app.cdr.max-record-count=100


logging.level.com.turkcell.cdrgenerator1=DEBUG
logging.file.name=logs/cdr-generator.log